### ISSUE TITLE
Typing spec update for tuples

### ISSUE THREAD

**Issue by erictraut** [python/typing-council#13]
I'd like to request that the TC consider adoption of a new chapter in the typing spec that spells out type checking behaviors related to tuples.

**TC Sign-off**
* [x] Eric
* [x] Guido
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Links to PR & Discussion**
The PR can be found [here](https://github.com/python/typing/pull/1599). The latest draft incorporates feedback from PR reviews and the discussion.

The discussion can be found [here](https://discuss.python.org/t/draft-of-typing-spec-chapter-for-tuples/43701).

**Current Type Checker Behaviors**
The latest published version of pyright (1.1.348) mostly conforms to the spec, although it doesn't correctly handle some nested unpacked tuple types.

The latest published version of mypy (1.8.0) mostly conforms to the proposed spec, but it has some false negatives for invalid unpacked tuple types. These should be straightforward to fix and shouldn't represent any backward compatibility issue for mypy users.

I haven't done a detailed analysis of pyre or pytype, but one obvious change that they will need to make is with regard to the special casing for `tuple[Any, ...]` specified in the proposed spec change.

**Controversial Issues**
I don't think there are any controversial issues with the latest draft of the proposed spec change.

**Comment by JelleZijlstra** [comment]
Thanks, I signed off. Linking to this post where I list some possibly confusing consequences of this decision: https://discuss.python.org/t/what-are-the-subtyping-rules-for-tuple-t/39837/77

**Comment by gvanrossum** [comment]
I signed off. GH did something weird, I hope I didn't accidentally sign off for @rchen152 ?

**Comment by JelleZijlstra** [comment]
Looks like Rebecca signed off for herself (in case you don't know: you can see the edited history if you click on the "edited by gvanrossum" gray text at the top of Eric's post).

**Comment by rchen152** [comment]
Yes, I signed off for myself =) I edited the comment at the same time to fix the spelling of my name, which I guess might have caused the weirdness.

**Comment by erictraut** [comment]
> to fix the spelling of my name

Oops. Apologies for misspelling your name. :(

**Comment by rchen152** [comment]
> > to fix the spelling of my name
> 
> Oops. Apologies for misspelling your name. :(

No worries!

**Comment by erictraut** [comment]
@hauntsaninja, let me know if you have any concerns or questions.

**Comment by hauntsaninja** [comment]
Thanks! I had two comments on the PR.

Also mypy and pyright currently differ on whether this is allowed:
```
def takes_at_least_one(x: tuple[int, *tuple[int, ...]]): ...

def takes_var(x: tuple[int, ...]):
    takes_at_least_one(x)
```
Just wanted to confirm whether the spec says something about this case and I missed it.

**Comment by erictraut** [comment]
> Also mypy and pyright currently differ on whether this is allowed

Mypy is correct here. This is a bug in pyright. I noticed it when writing the conformance tests. :) [Here](https://github.com/microsoft/pyright/issues/7115) is the bug I filed in the pyright issue tracker.
