### ISSUE TITLE
Typing spec update for named tuples

### ISSUE THREAD

**Issue by erictraut** [python/typing-council#17]
I'd like to request that the TC consider adoption of a new chapter in the typing spec that spells out type checking behaviors related to named tuples.

**Links to PR & Discussion**
The PR can be found [here](https://github.com/python/typing/pull/1614). The latest draft incorporates feedback from PR reviews and the discussion.

The discussion can be found [here](https://discuss.python.org/t/draft-of-typing-spec-chapter-for-named-tuples/44519).

**TC Sign-off**
* [x] Eric
* [x] Guido
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Current Type Checker Behaviors**
The proposed chapter specifies several required behaviors for type checkers along with some optional behaviors.

The latest published version of pyright (1.1.349) mostly conforms to the proposed spec but misses a few errors (false negatives).

The latest published version of mypy (1.8.0) mostly conforms to the proposed spec but likewise misses a few errors (false negatives).

I haven't done a detailed analysis of pyre or pytype, but I assume that they largely conform with the required parts of the proposed spec.

**Controversial Issues**
I'm not aware of any controversial issues or compatibility issues associated with the proposed spec.

**Comment by erictraut** [comment]
I've written a draft version of conformance tests for this chapter: https://github.com/python/typing/pull/1616.

As I expected, the four major type checkers largely comply, but the tests did uncover a few bugs and missing errors (false negatives).

**Comment by gvanrossum** [comment]
Thanks for the spec. It's very nice. I checked my box.

**Comment by erictraut** [comment]
This spec modification has been adopted by the TC.
