### ISSUE TITLE
PEP 742: Narrowing types with TypeIs

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing-council#21]
Please provide a recommendation on [PEP 742](https://peps.python.org/pep-0742/), which is being discussed in https://discuss.python.org/t/pep-742-narrowing-types-with-typeis/45613.

**Comment by gvanrossum** [comment]
We had a vote on Discord. A large majority of the TC is in favor of accepting  PEP 742 and everyone supports the name `TypeIs`. I will next announce this outcome on Discourse and submit PEP 742 to the SC (with a bit of background about why we prefer PEP 742 over PEP 724).

**Comment by gvanrossum** [comment]
Steering council issue: https://github.com/python/steering-council/issues/238
