### ISSUE TITLE
Typing spec update for Final and dataclasses

### ISSUE THREAD

**Issue by carljm** [python/typing-council#24]
see https://github.com/python/typing/pull/1669 for the proposed spec change

**TC Sign-off**
* [x] Eric
* [x] Guido
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Comment by JelleZijlstra** [comment]
The entire Typing Council has signed off, but our rule is to wait for a week to ensure enough time for discussion. Unless something new comes up, I'm planning to close this and merge the proposed spec change tomorrow night.
