### ISSUE TITLE
Typing spec update for defining "type expression" and other terms

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing-council#26]
Please consider python/typing#1693, also discussed in https://discuss.python.org/t/basic-terminology-for-types-and-type-forms/46741.

This PR defines the terms *type expression*, *annotation expression*, *type qualifier*, and *special form* and uses them in the spec. The change is intended only to provide more clarity and explicit definitions, so there are no changes to the conformance tests.

- [x] Eric
- [x] Guido
- [x] Jelle
- [x] Rebecca
- [x] Shantanu

**Comment by gvanrossum** [comment]
Is there somewhere I can view the rendered pages?

**Comment by gvanrossum** [comment]
(Never mind I just built the html myself. And I sent a review with some nits, I will sign off once you've fixed those.)

**Comment by hauntsaninja** [comment]
(for future reference: https://typing--1693.org.readthedocs.build/en/1693/ )

**Comment by gvanrossum** [comment]
I've signed off on this. Looks great!

**Comment by JelleZijlstra** [comment]
It's been a week and everyone has signed off, so this change is accepted. I will merge the change.
