### ISSUE TITLE
Typing spec update for exceptions / context managers

### ISSUE THREAD

**Issue by erictraut** [python/typing-council#27]
I'd like to request that the TC consider adoption of a new (small) chapter in the typing spec that spells out the type checking behaviors for context managers — specifically, how to use the return type of `__exit__` to determine whether a context manager suppresses exceptions.

**Links to PR & Discussion**
The PR can be found [here](https://github.com/python/typing/pull/1718). It incorporates feedback from PR reviewers.

The discussion can be found [here](https://discuss.python.org/t/draft-of-typing-spec-chapter-for-exceptions/51002).

**TC Sign-off**
* [x] Eric
* [x] Guido
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Current Type Checker Behaviors**
The specified behavior is consistent with the current behavior of mypy and pyright. It is also consistent with assumptions that are baked into typeshed stubs. I haven't done detailed testing on pyre or pytype, but given that they leverage typeshed stubs, they likely conform.

**Comment by gvanrossum** [comment]
(While I didn't approve the PR yet, my feedback there is just two nits, and even if you didn't address those I'm happy with this chapter, as it describes existing practice.)

**Comment by erictraut** [comment]
@gvanrossum, thanks for the feedback. I've incorporated your suggestions.

@rchen152, let me know if you have any concerns or feedback.

**Comment by rchen152** [comment]
No concerns from me.
