### ISSUE TITLE
Typing spec update for callables

### ISSUE THREAD

**Issue by erictraut** [python/typing-council#28]
I'd like to request that the TC consider adoption of a new chapter in the typing spec that fills in some missing information about callables, including rules for subtyping.

**Links to PR & Discussion**
The PR can be found [here](https://github.com/python/typing/pull/1723). The latest draft incorporates feedback from PR reviews and the discussion.

The discussion can be found [here](https://discuss.python.org/t/expanded-typing-spec-chapter-for-callables/51486).

**TC Sign-off**
* [x] Eric
* [x] Guido
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Current Type Checker Behaviors**
Most of the update is simply documenting behaviors that type checkers exhibit today.

There is one aspect of the update that will require changes to all type checkers. It is related to the treatment of `(*args: Any, **kwargs: Any)` as the same as `...` in a `Callable` annotation. The behavior in the draft specification is close to what mypy currently implements, but there are some differences that will require small changes in mypy. The other three major type checkers do not currently treat `(*args: Any, **kwargs: Any)` specially, so they will require updates to conform to the proposed spec.

**Controversial Issues**
The only controversial issue relates to the special treatment of `(*args: Any, **kwargs: Any)`. Some people (myself included) would prefer not to treat this specially, but taking into consideration mypy's historical behavior and the pain involved in changing it, a compromise makes sense here. It is not dissimilar to the decision we made for `tuple[Any, ...]`.

**Comment by rchen152** [comment]
I signed off. I'm not a huge fan of special-casing `(*args: Any, **kwargs: Any)`, but it seems like a reasonable compromise.

**Comment by gvanrossum** [comment]
I sent a PR review with some optional editorial nits, and signed off. Glad to see this concluded!
