### ISSUE TITLE
Adopt the initial Python typing spec

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typing-council#3]
I am asking the Typing Council to adopt the typing spec I put together: https://github.com/python/typing/pull/1517.

This is being discussed in https://discuss.python.org/t/proposed-initial-typing-spec/39389.

**Comment by erictraut** [comment]
I skimmed the document. It's a great starting point for the typing spec.

I didn't do a detailed comparison of the text to the original PEPs, but I presume that it's largely a verbatim copy of the specification sections of the original PEPs. If there are specific sections that you think require more careful review, please let us know.

**Comment by rchen152** [comment]
+1 This is a good starting point, and overall, I like the new organization.

**Comment by hauntsaninja** [comment]
I think this is a great place to start!

**Comment by gvanrossum** [comment]
+1. This is a great basis to iterate.

**Comment by JelleZijlstra** [comment]
Thanks, that makes everyone. I will merge the spec and we can start making improvements.
