### ISSUE TITLE
Typing spec update revising typeshed's position in the module resolution order

### ISSUE THREAD

**Issue by AlexWaygood** [python/typing-council#30]
I'd like to request that the Typing Council consider a proposed revision of the "module resolution order" specified by the typing spec at https://typing.readthedocs.io/en/latest/spec/distributing.html#import-resolution-ordering. The revision moves typeshed's standard-library stubs higher in the resolution order, in order to more accurately emulate Python's runtime semantics.

## Links to PR & Discussion

The PR can be found at https://github.com/python/typing/pull/1772. A more detailed description of the changes made can be found in the PR description.

A full explanation of the motivations for the proposed change can be found [in the dedicated Discourse thread](https://discuss.python.org/t/pep-561-s-module-resolution-order-seems-incorrect/55048). There appear to have been no significant objections to the proposal so far.

## TC Sign-off

- [x] Eric
- [x] Carl
- [x] Jelle
- [x] Rebecca
- [x] Shantanu

## Current Type Checker Behaviors

- Mypy: The new specification appears to be consistent with mypy's longstanding behaviour, which has technically not been fully compliant with the existing spec, but would be consistent with the revised version of the spec.
- Pyright: Pyright [recently changed its behaviour](https://github.com/microsoft/pyright/pull/8100) to implement this proposed revision to the spec.
- I have not surveyed pytype's and pyre's behaviours on this matter.

**Comment by JelleZijlstra** [comment]
It's been a week and everyone signed off, this is accepted. Thank you for pushing this change through!
