### ISSUE TITLE
Typing spec update: core concepts and definitions

### ISSUE THREAD

**Issue by carljm** [python/typing-council#31]
Hello! I'd like to request formal typing council consideration of https://github.com/python/typing/pull/1743, which adds to the typing spec a presentation of the core concepts of the Python type system, defines a number of key terms, and attempts to update the spec to use those terms consistently. The pull request has received excellent and thorough review from many members of the typing council and typing community.

I started a Discourse thread at https://discuss.python.org/t/formalizing-core-definitions-in-the-typing-spec/54785 -- it received a number of likes, but no replies.

TC sign off:

- [x] Carl
- [x] Eric
- [x] Jelle
- [x] Rebecca
- [x] Shantanu

**Comment by erictraut** [comment]
@carljm, thanks again for driving this change! I thoroughly read an earlier draft and have been trying to follow all of the subsequent updates, but I'd like to read the final draft from top to bottom before signing off. It may be a few days before I have time to complete this review.

**Comment by erictraut** [comment]
I completed my top-to-bottom review. I left a few comments for very minor suggestions, but I'm fine if these are ignored or deferred to a subsequent PR. I've signed off on the change.

**Comment by hauntsaninja** [comment]
Thank you for improving this!

(One minor process nit is that changes like this should probably be their own PR, even if uncontroversial https://github.com/python/typing/pull/1743/files#diff-184b677a01f925aa7d9a29fabc8c946f2d99da37850f89210ad5a2ff33fa52cfR25 )

**Comment by carljm** [comment]
Thanks all for the reviews! Per the documented process, I'll wait to merge the PR until a week has passed since I filed this issue.
