### ISSUE TITLE
Typing spec update: PEP 712 `converter` in `dataclasses` Field spec params

### ISSUE THREAD

**Issue by thejcannon** [python/typing-council#33]
PR: https://github.com/python/typing/pull/1783
Discussion on PEP 712 (rejected adding to stdlib `dataclasses`, but community seemed in-favor of `dataclass_transform` addition).

This already is implemented in Pyright: https://github.com/microsoft/pyright/pull/5034

❤️ Thanks y'all!

TC sign-off
-----------

- [x] Carl
- [x] Eric
- [x] Jelle
- [x] Rebecca
- [x] Shantanu

**Comment by erictraut** [comment]
@thejcannon, thanks for doing this. Could you please announce this PR in the discourse thread so the community has a chance to review it? We should then wait a week to see if any further comments come in.

**Comment by erictraut** [comment]
For reference, here's a link to the [discourse thread](https://discuss.python.org/t/discuss-adding-converter-to-dataclass-transform/55125).

**Comment by thejcannon** [comment]
For reference, here's the Typing council approval in Discourse: https://discuss.python.org/t/discuss-adding-converter-to-dataclass-transform/55125/5
