### ISSUE TITLE
Typing spec update: a non-ReadOnly item in a TypedDict cannot be redeclared as ReadOnly

### ISSUE THREAD

**Issue by rchen152** [python/typing-council#36]
Please consider the following update to the typing spec:

* PR: https://github.com/python/typing/pull/1859
* Discussion: https://discuss.python.org/t/can-a-non-readonly-item-in-a-typeddict-be-redeclared-as-readonly/65082

**TC Sign-off**
* [x] Carl
* [x] Eric
* [x] Jelle
* [x] Rebecca
* [x] Shantanu

**Comment by carljm** [comment]
Approved by all TC members and PR merged.
