### ISSUE TITLE
Typing spec update: clarifications to user-defined generic classes

### ISSUE THREAD

**Issue by rchen152** [python/typing-council#38]
Please consider the following update to the typing spec:

* PR: https://github.com/python/typing/pull/1879
* Discussion: https://discuss.python.org/t/clarifying-the-rules-for-subclassing-generic-classes/69698

**TC Sign-off**
* [x] Carl
* [x] Eric
* [x] Jelle
* [x] Jukka
* [x] Rebecca

**Comment by rchen152** [comment]
@JelleZijlstra, @JukkaL do you have any additional thoughts on https://github.com/python/typing/pull/1879?

**Comment by JelleZijlstra** [comment]
Oops, I thought I'd already signed off.

**Comment by rchen152** [comment]
PR merged =D
