### ISSUE TITLE
Allow `NoReturn` to appear outside of function return type annotations

### ISSUE THREAD

**Issue by erictraut** [python/typing-council#5]
I would like request that the typing council consider amending the typing spec to allow `NoReturn` to appear in locations other than return type annotations. It is equivalent to `Never`, and the two types should be completely interchangeable.

This was discussed in the [python/typing forum](https://github.com/python/typing/issues/1558), and there were no objections to the change.

All four major type checkers already treat `NoReturn` in the manner consistent with the proposed change, so this would bring the spec in conformance with the type checker implementations.

I've prepared [this PR](https://github.com/python/typing/pull/1570) with the proposed change to the typing spec.

**Comment by gvanrossum** [comment]
+1.

Do we have a process for this kind of thing yet? Do we all just approve the PR and then you merge it?

**Comment by JelleZijlstra** [comment]
Also agree. I think for this sort of small, relatively uncontroversial change it's OK to just approve on GitHub. We can have a bigger discussion on Discord for anything more controversial.

**Comment by JelleZijlstra** [comment]
Everyone on the Council approved the PR; this proposal has been accepted.
